# flutter pub get
# flutter pub upgrade -major-versions # æ›´æ–°Flutteré¡¹ç›®çš„ä¾èµ–åŒ…åˆ°majorç‰ˆæœ¬
# flutter pub outdated
# open pub.dev

# dart pub global activate flutter_unused_packages # å®‰è£… flutter_unused_packages
# flutter_unused_packages --init # åœ¨é¡¹ç›®æ ¹ç›®å½•ä¸‹åˆå§‹åŒ–é…ç½®ï¼ˆå¯é€‰ï¼‰ðŸ“ƒanalize_unused_packages.json
# flutter_unused_packages --analyze # åˆ†æžé¡¹ç›®ä¸­æœªä½¿ç”¨çš„ä¾èµ–
# flutter_unused_packages --fix # è‡ªåŠ¨æ¸…ç†è¢«åˆ¤å®šä¸ºæœªä½¿ç”¨çš„ä¾èµ–

name: jobs_flutter_base_config
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"
# åœ¨dependencieséƒ¨åˆ†ä¸­å·²ç»å£°æ˜Žäº†æŸä¸ªåŒ…ï¼Œå°±ä¸éœ€è¦åœ¨dev_dependencieséƒ¨åˆ†é‡å¤å£°æ˜Žäº†ã€‚
dependencies:
  # æ ¸å¿ƒåº“
  flutter:
    sdk: flutter
  # UIç»„ä»¶åº“
  ym_flutter_widget: any
  flutter_svg: any
  oktoast: any # è½»é‡çº§toast
  extended_tabs: any # æ‰©å±•TabBar
  cupertino_icons: any
  device_preview: any # å¤šè®¾å¤‡æ¨¡æ‹Ÿå™¨ï¼ˆå¤–éƒ¨åŒ…è£¹ï¼‰
  easy_localization: any # å›½é™…åŒ–æ ¹å®¹å™¨ï¼ˆå¤–éƒ¨åŒ…è£¹ï¼‰
  flutter_phoenix: any # çƒ­é‡å¯å®¹å™¨ï¼ˆå¤–éƒ¨åŒ…è£¹ï¼‰
  screenshot: any # æˆªå±æ“ä½œ
  vibration: any # éœ‡åŠ¨
  carousel_slider: any # ç”¨äºŽè½®æ’­å›¾
  card_swiper: any # ç”¨äºŽè½®æ’­å›¾
  easy_refresh: any # ç”¨äºŽä¸‹æ‹‰åˆ·æ–°
  webview_flutter: any # ç”¨äºŽæ˜¾ç¤ºç½‘é¡µ
  camera: any # ç”¨äºŽæ‹ç…§
  image_picker: any # image_picker æ’ä»¶åªèƒ½åˆ†åˆ«è°ƒç”¨æ‹ç…§æˆ–å½•åƒåŠŸèƒ½ï¼Œä½†ä¸èƒ½ç›´æŽ¥è°ƒç”¨ç³»ç»Ÿç›¸æœºåº”ç”¨çš„å®Œæ•´ç•Œé¢
  flutter_inappwebview: any # ç”¨äºŽæ˜¾ç¤ºç½‘é¡µ (iOS)
  flutter_fortune_wheel: any # ç”¨äºŽæ˜¾ç¤ºæŠ½å¥–è½¬ç›˜
  flutter_easyloading: any #
  # google_mobile_ads: any # ç”¨äºŽæ˜¾ç¤ºå¹¿å‘Šã€‚åˆå§‹åŒ–çš„æ—¶å€™å¿…é¡»è¦å¸¦ Key å¦åˆ™ç¨‹åºå´©æºƒ
  cached_network_image: any # ç”¨äºŽæ˜¾ç¤ºç½‘ç»œå›¾ç‰‡
  # å›¾ç‰‡å¤„ç†
  # flutter_native_image: any # ç”¨äºŽå¤„ç†åŽŸç”Ÿå›¾ç‰‡ ðŸš¨ æ‰“åŒ…å¤±è´¥
  flutter_advanced_networkimage_2: any # ç”¨äºŽå¤„ç†ç½‘ç»œå›¾ç‰‡(å›¾ç‰‡ç¼“å­˜ + æŽ§åˆ¶flutter_cache_manager)
  flutter_cache_manager: any # ç”¨äºŽå¤„ç†ç½‘ç»œå›¾ç‰‡(ç‹¬ç«‹ç¼“å­˜æŽ§åˆ¶)
  # æ•°æ®å¤„ç†
  equatable: any # ç”¨äºŽå®šä¹‰å€¼å¯¹è±¡çš„ç›¸ç­‰æ€§
  built_value: any # ç”¨äºŽåºåˆ—åŒ–/ååºåˆ—åŒ–æ•°æ®
  built_collection: any # ç”¨äºŽåºåˆ—åŒ–/ååºåˆ—åŒ–æ•°æ®
  shared_preferences: any # ç”¨äºŽå­˜å‚¨é”®å€¼å¯¹æ•°æ®
  encrypt: any # ç”¨äºŽåŠ å¯†æ•°æ®
  pointycastle: any # ç”¨äºŽåŠ å¯†æ•°æ®
  video_compress: any # ç”¨äºŽå¤„ç†è§†é¢‘
  json_annotation: any # ç”¨äºŽå¤„ç†jsonæ•°æ®
  # çŠ¶æ€ç®¡ç†
  get: any # ç”¨äºŽç®¡ç†åº”ç”¨çŠ¶æ€
  provider: any # ç”¨äºŽç®¡ç†åº”ç”¨çŠ¶æ€
  flutter_riverpod: any # ç”¨äºŽç®¡ç†åº”ç”¨çŠ¶æ€
  bloc: any # ç”¨äºŽç®¡ç†åº”ç”¨çŠ¶æ€
  flutter_bloc: any # ç”¨äºŽç®¡ç†åº”ç”¨çŠ¶æ€
  # ç”¨æˆ·æƒé™å¤„ç†
  # ç½‘ç»œè¯·æ±‚
  dart_ping_ios: any #
  http: any # ç”¨äºŽç½‘ç»œè¯·æ±‚
  # Chopper: any # ç”¨äºŽç½‘ç»œè¯·æ±‚
  # FlutterHttpClient: any # ç”¨äºŽç½‘ç»œè¯·æ±‚
  dio: any # ç”¨äºŽç½‘ç»œè¯·æ±‚
  mqtt_client: any # ç”¨äºŽè¿žæŽ¥MQTTæœåŠ¡å™¨
  # flutter_cache_manager_firebase: any # ç”¨äºŽç¼“å­˜ç½‘ç»œè¯·æ±‚ (Firebase)
  # æœ¬åœ°å­˜å‚¨
  # get_storage: any # ç”¨äºŽå­˜å‚¨é”®å€¼å¯¹æ•°æ®
  # shared_preferences_web: any # ç”¨äºŽå­˜å‚¨é”®å€¼å¯¹æ•°æ® (web)
  # shared_preferences_platform_interface: any # ç”¨äºŽå­˜å‚¨é”®å€¼å¯¹æ•°æ® (platform interface)
  # flutter_secure_storage: any # ç”¨äºŽå­˜å‚¨æ•æ„Ÿæ•°æ®
  # flutter_secure_storage_macos: any # ç”¨äºŽå­˜å‚¨æ•æ„Ÿæ•°æ® (macOS)
  sqflite: any # ç”¨äºŽæœ¬åœ°æ•°æ®åº“
  # æ’­æ”¾å™¨
  video_player: any # ç”¨äºŽæ’­æ”¾è§†é¢‘
  audioplayers: ^5.2.1 # ç”¨äºŽæ’­æ”¾éŸ³é¢‘
  # å›½é™…åŒ–
  intl: any # æä¾›å›½é™…åŒ–å’Œæœ¬åœ°åŒ–è®¾æ–½ï¼ŒåŒ…æ‹¬æ¶ˆæ¯ç¿»è¯‘ã€å¤æ•°å’Œæ€§åˆ«ã€æ—¥æœŸ/æ•°å­—æ ¼å¼å’Œè§£æžä»¥åŠåŒå‘æ–‡æœ¬
  # è®¾å¤‡/åº”ç”¨ç›¸å…³
  timezone: any # ç”¨äºŽèŽ·å–è®¾å¤‡æ—¶åŒº
  # platform_device_id: any # ç”¨äºŽèŽ·å–è®¾å¤‡å”¯ä¸€æ ‡è¯†ç¬¦ ðŸš¨ç”¨äº†device_infoæ‰“åŒ…å¤±è´¥
  # åˆ†äº«åŠŸèƒ½
  # è´¦å·ç™»é™†
  # é”®ç›˜ç›¸å…³
  # åœ°å›¾ç›¸å…³
  flutter_localizations: # ä¸€ä¸ªä½¿ç”¨åœ°å›¾æ•°æ®è¿›è¡Œåº”ç”¨å†…å®šä½çš„è½¯ä»¶åŒ…
    sdk: flutter
  # å·¥å…·åº“
  wakelock_plus: any # ç”¨äºŽä¿æŒå±å¹•å¸¸äº®
  flutter_plugin_engagelab: any # æžå…‰æŽ¨é€
  file_picker: any # å®žçŽ°æ–‡ä»¶é€‰æ‹©å™¨åŠŸèƒ½ï¼Œå…è®¸ç”¨æˆ·ä»Žæœ¬åœ°æ–‡ä»¶ç³»ç»Ÿä¸­é€‰æ‹©ä»»æ„æ–‡ä»¶ï¼ˆå¦‚å›¾ç‰‡ã€PDFã€æ–‡æ¡£ã€è§†é¢‘ç­‰ï¼‰ï¼Œå¹¶èŽ·å–è·¯å¾„ç”¨äºŽä¸Šä¼ ç­‰æ“ä½œã€‚
  connectivity_plus: any # ç”¨äºŽæ£€æŸ¥è®¾å¤‡ç½‘ç»œè¿žæŽ¥çŠ¶æ€
  url_launcher: any # ç”¨äºŽåœ¨ç§»åŠ¨åº”ç”¨ä¸­æ‰“å¼€ URLsï¼ŒåŒ…æ‹¬ç½‘é¡µã€ç”µå­é‚®ä»¶ã€ç”µè¯ç­‰
  path: any # ç”¨äºŽå¤„ç†æ–‡ä»¶è·¯å¾„
  path_provider: any # ç”¨äºŽèŽ·å–æ–‡ä»¶è·¯å¾„
  google_fonts: any # ç”¨äºŽä½¿ç”¨Google Fontså­—ä½“
  flutter_local_notifications: any # ç”¨äºŽæ˜¾ç¤ºæœ¬åœ°é€šçŸ¥
  auto_route: any # ç”¨äºŽç®¡ç†åº”ç”¨è·¯ç”±
  flutter_screenutil: any # ç”¨äºŽå±å¹•é€‚é…
  # åº”ç”¨ç¨‹åº
  # æ—¥å¿—è°ƒè¯•
  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any # Flutterä»£ç è§„èŒƒ
  build_runner: any
  json_serializable: any
  built_value_generator: any # ç”¨äºŽç”Ÿæˆåºåˆ—åŒ–/ååºåˆ—åŒ–ä»£ç 
flutter_gen:
  output: lib/gen/ # ç”Ÿæˆæ–‡ä»¶çš„ç›®å½•
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true # æŒ‡ç¤ºåº”ç”¨ç¨‹åºæ˜¯å¦åº”è¯¥ä½¿ç”¨ Material Design é£Žæ ¼
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets: # è·¯å¾„åä¸èƒ½æœ‰ä¸­æ–‡ï¼Œå¦åˆ™å¯èƒ½æ— æ³•æ­£å¸¸è¯»å–
    - assets/
    - assets/Fonts/
    - assets/HTML/
    - assets/i18n/
    - assets/Images/
    - assets/Jsons/
    - assets/Lottie/
    - assets/Others/
    - assets/README/
    - assets/SVG/
    - assets/Sounds/
    - assets/Video/
    - lib/resource/

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
#
# https://fonts.google.com/
fonts:
  - family: Akrobat-Bold
    fonts:
      - asset: assets/fonts/Akrobat-Bold.otf
  - family: Proximanova-bold
    fonts:
      - asset: assets/fonts/ProximaNovaBold.otf
  - family: Schyler
    fonts:
      - asset: assets/fonts/Schyler-Regular.ttf
      - asset: assets/fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: assets/fonts/TrajanPro.ttf
      - asset: assets/fonts/TrajanPro_Bold.ttf
        weight: 700
